### ISSUE TITLE
Cookie al añadir Usuario

### ISSUE THREAD

**Issue by josemifd** [UNIZAR-30226-2024-07/backend#7]
En la función add del Schema User hay que crear la cookie para que pueda entrar y usar las funciones de la API sin necesidad de haberse logueado

**Comment by Flavio-Tolosana** [comment]
Ya lo he hecho, he agregado esto antes de dar la respuesta correcta con status 200:

``` js
// Se crea el token y se responde
  const token = await createAccessToken({ id: newUser._id })
  res.cookie('token', token, {
      sameSite: 'none',
      secure: true
  })
```
